# Generated by Django 5.1.1 on 2024-10-11 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('fullName', models.CharField(max_length=264, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('iso', models.CharField(default='xx', max_length=6)),
                ('flagURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264)),
                ('sport', models.CharField(blank=True, max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=30)),
                ('location', models.CharField(max_length=264)),
                ('season', models.CharField(choices=[('Winter', 'Winter'), ('Summer', 'Summer')], max_length=6)),
                ('year', models.IntegerField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264)),
                ('shortName', models.CharField(blank=True, max_length=264)),
                ('displayName', models.CharField(blank=True, max_length=264)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('disciplines', models.CharField(blank=True, max_length=1000)),
                ('events', models.CharField(blank=True, max_length=1000)),
                ('dob', models.DateField(null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('isAlternate', models.BooleanField(null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='tally_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=264)),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('X', 'Mixed')], max_length=5)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tally_app.discipline')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tally_app.host')),
            ],
            options={
                'unique_together': {('discipline', 'name', 'gender')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('X', 'Mixed')], max_length=5)),
                ('discipline', models.CharField(max_length=264)),
                ('athleteNames', models.CharField(blank=True, max_length=1000)),
                ('athleteIDs', models.CharField(blank=True, max_length=1000)),
                ('numAthletes', models.IntegerField(null=True)),
                ('codeRaw', models.CharField(blank=True, max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tally_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], max_length=6)),
                ('object_id', models.CharField(max_length=264)),
                ('date', models.DateField(null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals', to='tally_app.country')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals', to='tally_app.event')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='tally_app_m_content_f9c72d_idx')],
            },
        ),
    ]
